toolkitties/toolkitty

- LICENSE
- README.md
This PR updates the README with more information about the project and adds a GNU General Public License.
> Readme updates and license

- src/components/dialog/dialog-content.svelte
- src/components/dialog/index.ts
This PR implements a styled dialog component that can be used across the app for alerting the user to take a certain action.
> Dialog component

- src/app.css
- src/components/event-row.svelte
- src/routes/app/events/+page.svelte
- tailwind.config.js
This PR add an event row component for usage on home and dashboard/profile pages. Types for events still to be added to this component.
> Add events row component

- src/lib/api/calendars.ts
- src/lib/api/events.ts
- src/lib/api/index.ts
- src/lib/api/inviteCode.ts
- src/lib/api/inviteCodes.ts
- src/lib/api/resources.ts
- src/lib/channel.ts
- src/lib/promiseMap.ts
- src/lib/types.ts
- src/routes/(unauthed)/+page.svelte
- src/routes/(unauthed)/create/+page.svelte
This PR declares types to be used in the API that will connect the frontend/backend & refactors API methods.
> API type declaration and message processing

- src/components/toasts.svelte
- src/lib/toast.svelte.ts
- src/routes/+layout.svelte
This PR adds toasts for showing temporary messages to the user when certain events happen. They can contain a link which will direct the user to a specific page if clicked.
Can be invoked using `toast.error`, `toast.success` or  `toast.info` methods.
_Example usage_
```
toast.success("Event created");
toast.error("Calendar not found");
toast.info("Someone requested your resource", "link-to-request");
```
> Add Toast 🍞

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/node/mod.rs
- src-tauri/src/node/operation.rs
- src-tauri/src/node/stream.rs
- src-tauri/src/topic.rs
- src/routes/(unauthed)/create/+page.svelte
> Handle acknowledged operations and re-play unacked ones in backend

- src/components/availability.svelte
- src/routes/app/availability-test/+page.svelte
This adds an availability viewer that displays the availability of a resource on a given day with blocks for each booking already made. UI wise its similar to what is found on a calendar.
I created a test page `/app/availability-test` for viewing the component.
We get the length of `availability` in hours (`availabilityLength`) and then convert each `booked` item into a `bookedBlocks` with a `start` properly that is a percentage of the `availabilityLength` and a `length` property that is a percentage of the `availabilityLength`. These percentages then allow us to display the `bookedBlocks` as absolutely positioned elements inside a relative container. The height of this container is determined by an array of `hours` from the  `availability`.
With this method we can display booking that …
> Availability viewer

- src/lib/api/calendars.ts
- src/lib/api/data.ts
- src/lib/api/events.ts
- src/lib/api/index.ts
- src/lib/api/requests.ts
- src/lib/api/resources.ts
- src/lib/api/spaces.ts
- src/lib/db.ts
- src/lib/processor.ts
- src/lib/types.ts
- src/routes/(unauthed)/create/+page.svelte
- src/routes/+layout.svelte
- fix for backend error when processing seed data
> Complete queries and middleware for `Calendar`, `Space` and `Resource`

- src/lib/api/events.ts
- src/lib/processor.ts
- methods for querying events from the database
- methods for creating, updating and deleting documents (which issue network events)
- processor middleware for handling incoming event messages
> Implement events API and middleware

- src-tauri/src/app.rs
This PR removes the requirement that `init()` only be called once on app start-up. Subsequent calls (only situation where this occurs so far is hot reloading in dev mode) are tolerated and any existing channel is replaced with the new one. 
I believe that it would be possible to "lose" events that were already sent to the old channel, but not consumed yet, which I would say is the big potential downside of this approach (and the reason for originally not allowing it). However I have no proof that this would be an issue and we are willing to try in order to improve developer experience.
> Allow multiple calls to `init` command

- package-lock.json
- src/lib/api/bookings.ts
- src/lib/api/data.ts
- src/lib/components/RequestToast.svelte
- src/lib/components/dialog/BookingRequestDialog.svelte
- src/lib/components/dialog/DialogContent.svelte
- src/lib/toast.svelte.ts
- src/lib/types.ts
- src/routes/app/dashboard/+page.svelte
- src/routes/app/dashboard/+page.ts
- src/routes/app/dashboard/RequestDialog.svelte
This PR adds UI for responding to a booking request.
- Enrich return types for pending requests (seperate issue).
- Check booking request toast appears when a booking request is made. Test once event form submits creates bookings.
> Bookings response UI

- src/lib/components/Error.svelte
- src/routes/+error.svelte
- src/routes/app/+error.svelte
- src/routes/app/events/+page.ts
This PR creates a custom error component that will show to the user when we throw errors.
> Create error component

- src/routes/app/dashboard/+page.svelte
This PR fixes bug where users where shown all pending requests instead of just requests for resources that they own.
> Show only pending requests for resources that users owns.

- package-lock.json
- src/app.css
- src/lib/components/AvailabilityViewer.svelte
- src/lib/components/Bookings.svelte
- src/lib/components/Date.svelte
- src/lib/components/EventRow.svelte
- src/lib/components/Links.svelte
- src/lib/components/UpcomingBookings.svelte
- src/routes/app/+layout.svelte
- src/routes/app/events/EventForm.svelte
- src/routes/app/events/[id]/+page.svelte
- src/routes/app/resources/[id]/+page.svelte
- src/routes/app/spaces/[id]/+page.svelte
This PR builds events, spaces and resources pages closer to final designs, adds a reusable date component and fixes some existing issues with app navigation:
- Move `nav` outside of `main` (Fixes #61)
- Add background colour
- Position `sticky` so it doesn't hide content below
> Spaces resources events pages

- src/routes/app/admin/+page.svelte
- src/routes/app/admin/RequestDialog.svelte
This PR displayed "you" for yourself in share/admin page by checking user public key against local public key.
> Show you in share page for yourself

- src/app.css
- src/lib/components/Header.svelte
- src/routes/app/+layout.svelte
- src/routes/app/calendars/edit/+page.svelte
- src/routes/app/events/[id]/edit/+page.svelte
- src/routes/app/events/create/+page.svelte
- src/routes/app/resources/+page.svelte
- src/routes/app/resources/create/+page.svelte
- src/routes/app/spaces/+page.svelte
- src/routes/app/spaces/[id]/edit/+page.svelte
- src/routes/app/spaces/create/+page.svelte
- tailwind.config.js
This PR adds following styling updates:
- Padding on `main` consistant with `header`.
- Correct background colour for `header` and `nav`.
- Fix scroll bounce on Safari/iOS/MacOS.
- Remove `<br />` elements from all pages.
> general styling updates and fix scroll bounce on safari/ios

- src/lib/components/RequestToast.svelte
- src/lib/toast.svelte.ts
This PR fixes bug with toasts where dismissing a dialog would not dismiss toast attached to it and also future toasts appearing to the user.
> Bugfix dialog not dismissing toast

- src/routes/(unauthed)/join/+page.svelte
- src/routes/(unauthed)/request/+page.ts
This PR fixes a bug where active calendar was not updating when joining a new calendar.
> Bugfix active calendar not updating

- src/routes/app/resources/ResourceForm.svelte
- src/routes/app/spaces/SpaceForm.svelte
This PR fixed bug where the user was not navigated to resource/space after updating/creating it.
> Bugfix goto spaces/resource after updating/creating 

- package-lock.json
- package.json
- src/lib/components/UpcomingBookings.svelte
- src/routes/app/events/+page.svelte
- src/routes/app/events/+page.ts
- src/routes/app/events/[id]/+page.svelte
- src/routes/app/events/[id]/+page.ts
- src/routes/app/resources/+page.svelte
- src/routes/app/resources/+page.ts
- src/routes/app/resources/[id]/+page.svelte
- src/routes/app/resources/[id]/+page.ts
- src/routes/app/spaces/+page.svelte
- src/routes/app/spaces/+page.ts
- src/routes/app/spaces/[id]/+page.svelte
- src/routes/app/spaces/[id]/+page.ts
This PR moves all data inside the following pages to live queries so data updates in realtime as information is recieved from other peers.
- `#/app/events`
- `#/app/events/id`
- `#/app/resources`
- `#/app/resources/id`
- `#/app/spaces`
- `#/app/spaces/id`
> Live queries

- src/routes/app/events/EventForm.svelte
- src/routes/app/resources/ResourceForm.svelte
- src/routes/app/spaces/SpaceForm.svelte
This PR checks if forms are valid before submitting.
> Enable form validation

- src/routes/app/events/[id]/+page.svelte
- src/routes/app/resources/[id]/+page.svelte
- src/routes/app/spaces/[id]/+page.svelte
This PR fixes bug where owners of resources/spaces/events could not see edit button.
> Bugfix can edit as owner

- src/lib/components/Date.svelte
- src/lib/components/DateRange.svelte
- src/routes/app/events/+page.svelte
- src/routes/app/events/[id]/+page.svelte
* Group events by date in events list
* `format` property for `Date` component to adjust formatting
* Introduce `DateRange` component
* Nice formatting for all dates
Towards: https://github.com/toolkitties/toolkitty/issues/253
> Group events by date, fancy date and range formatting

- src/lib/components/EventRow.svelte
- src/lib/components/ImageGallery.svelte
- src/lib/components/ImageUploader.svelte
- src/lib/utils/faker.ts
- src/routes/app/events/EventForm.svelte
- src/routes/app/events/[id]/+page.svelte
- src/routes/app/resources/+page.svelte
- src/routes/app/resources/ResourceForm.svelte
- src/routes/app/resources/[id]/+page.svelte
- src/routes/app/spaces/+page.svelte
- src/routes/app/spaces/SpaceForm.svelte
- src/routes/app/spaces/[id]/+page.svelte
> Upload images in forms and show them

- src/lib/schemas.ts
- src/lib/types.ts
- src/routes/app/events/EventForm.svelte
- src/routes/app/resources/ResourceForm.svelte
- src/routes/app/resources/[id]/+page.svelte
- src/routes/app/resources/[id]/edit/+page.ts
- src/routes/app/spaces/SpaceForm.svelte
This PR allows links to be submitted as `undefined`.
> Undefined links in forms

- src/lib/schemas.ts
- src/routes/app/events/EventForm.svelte
This PR fixes bugs with event and availability forms.
- remove `dateProxy` so date is now a `string` rather than `date`. Maybe introduce edge case bugs with certain HTML date pickers (to be refactored here #278)
- remove selectedSpace from event form schema to allow form submission (to be refactored here #279)
> Availability form bug fixes

- src/routes/app/events/EventForm.svelte
All filtering scenarios not implemented yet, temp solution to have something rendered
> Show resource list on initial load of edit event form

- src/routes/app/events/EventForm.svelte
- src/routes/app/resources/+page.svelte
- src/routes/app/resources/ResourceForm.svelte
- src/routes/app/resources/view/+page.ts
- src/routes/app/spaces/+page.svelte
- src/routes/app/spaces/SpaceForm.svelte
This PR fixes redirects after form submission for events/resource/space create/edit.
> Bugfix redirects after form submission

- src/lib/api/events.ts
- src/lib/db.ts
This PR orders events from the API by startDate.
> order events by startDate

- src/lib/types.ts
This PR explicitly sets date types in `types.ts` to be `ISO8601UTC` strings.
Closes #216
> Date types ISO8601 UTC
